name: horizongram
services:
  backend:
    container_name: hzg-be
    build: ./../server
    volumes:
      - ./../server:/usr/src/app
      - ./../downloads:/usr/src/app/downloads
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - "3000"
    networks:
      - horizongram-net
  
  frontend:
    container_name: hzg-fe
    image: nginx:alpine
    volumes:
      - ./../client:/usr/share/nginx/html
      - ./../wiki:/usr/share/nginx/html/wiki
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - horizongram-net

  reverse-proxy:
    container_name: hzg-nginx
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - horizongram-net

networks:
  horizongram-net: